#!/usr/bin/env python

from lib import get_gitlab_instance
import sys


if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab open issues')
    print('graph_vlabel issues')
    print('graph_args -l 0')
    print('graph_category gitlab')
    print('unassigned.label unassigned')
    print('unassigned.draw AREA')
    print('unassigned.colour BCFFBC')
    print('assigned.label assigned')
    print('assigned.draw STACK')
    print('assigned.colour 00FF00')
    sys.exit(0)

gitlab = get_gitlab_instance()
db = gitlab.get_db_connection()

cursor = db.cursor()
cursor.execute("SELECT COUNT(*) FROM issues WHERE state IN ('opened', 'reopened') AND deleted_at IS NULL AND assignee_id IS NULL")
unassigned = cursor.fetchone()[0]
cursor.close()

cursor = db.cursor()
cursor.execute("SELECT COUNT(*) FROM issues WHERE state IN ('opened', 'reopened') AND deleted_at IS NULL AND assignee_id IS NOT NULL")
assigned = cursor.fetchone()[0]
cursor.close()

db.close()

print('unassigned.value ' + str(unassigned))
print('assigned.value ' + str(assigned))

