#!/usr/bin/env python

from lib import get_gitlab_instance
import sys


if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab open issues')
    print('graph_vlabel issues')
    print('graph_args -l 0')
    print('graph_category gitlab')
    print('count.label open issue count')
    print('count.draw AREA')
    sys.exit(0)

gitlab = get_gitlab_instance()
db = gitlab.get_db_connection()
cursor = db.cursor()
cursor.execute("SELECT COUNT(*) FROM issues WHERE state = 'opened'")
count = cursor.fetchone()[0]
cursor.close()
db.close()

print('count.value ' + str(count))

