#!/usr/bin/env python
from lib import get_gitlab_instance

import sys

SHOW_CONFIG = len(sys.argv) >= 2 and sys.argv[1] == 'config'

if SHOW_CONFIG:
    print('graph_title GitLab CI builds')
    print('graph_vlabel builds')
    print('graph_args -l 0')
    print('graph_category gitlab')

gitlab = get_gitlab_instance()
db = gitlab.get_db_connection()
try:
    cursor = db.cursor()
    cursor.execute(
        'SELECT status, COUNT(status) AS amount '
        'FROM ci_builds '
        'GROUP BY status'
    )
    for row in cursor.fetchall():
        if SHOW_CONFIG:
            print('{0}.draw AREASTACK'.format(*row))
            print('{0}.label {0}'.format(*row))
        else:
            print('{0}.value {1:d}'.format(*row))

    cursor.close()
finally:
    db.close()
