#!/usr/bin/env python

# inspired by the redis munin plugin found at
# http://munin-monitoring.org/browser/munin-contrib/plugins/redis/redis_,
# written 2009 by Gleb Voronich <http://stanly.net.ua/>

from lib import get_gitlab_instance
import sys


if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title Redis: Per second')
    print('graph_vlabel per ${graph_period}')
    print('graph_category gitlab')
    print('graph_args -l 0')
    print('requests.label requests')
    print('requests.type COUNTER')
    print('connections.label connections')
    print('connections.type COUNTER')
    sys.exit(0)

gitlab = get_gitlab_instance()
redis_info = gitlab.get_redis_info()
print('requests.value ' + redis_info['total_commands_processed'])
print('connections.value ' + redis_info['total_connections_received'])

