#!/usr/bin/env python
from lib import dirsize
from lib import get_gitlab_instance
import sys


gitlab = get_gitlab_instance()
cache_root = gitlab.get_cache_dir()

if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab build cache disk usage')
    print('graph_vlabel build cache disk usage')
    print('graph_args -l 0 --base 1024')
    print('graph_category gitlab')
    print('cache_size.label build cache')
    print('cache_size.draw AREA')
    sys.exit(0)

cache_size = 0

try:
    cache_size = dirsize(cache_root)
except OSError as e:
    print(e)
    sys.exit(1)

print('cache_size.value ' + str(cache_size))
