#!/usr/bin/env python

from lib import dirsize
from lib import get_gitlab_instance
import os
import sys

gitlab = get_gitlab_instance()
repository_root = gitlab.get_repository_dir()

if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab Repository Disk Usage')
    print('graph_vlabel Repository Disk Usage')
    print('graph_args -l 0 --base 1024')
    print('graph_category gitlab')
    print('repo_size.label Repositories')
    print('repo_size.draw AREA')
    print('wiki_size.label Wikis')
    print('wiki_size.draw STACK')
    sys.exit(0)

repo_size = 0
wiki_size = 0

try:
    namespaces = os.listdir(repository_root)
    for namespace in namespaces:
        repos = os.listdir(repository_root + '/' + namespace)
        for repo in repos:
            repo_path = repository_root + '/' + namespace + '/' + repo
            if repo.endswith('.wiki.git'):
                wiki_size += dirsize(repo_path)
            elif repo.endswith('.git'):
                repo_size += dirsize(repo_path)
except OSError as e:
    print(e)
    sys.exit(1)

print('repo_size.value ' + str(repo_size))
print('wiki_size.value ' + str(wiki_size))

