#!/usr/bin/env python

from lib import get_gitlab_instance
import sys

if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab CI current build queue')
    print('graph_vlabel builds')
    print('graph_args -l 0')
    print('graph_category gitlab')
    print('pending.label pending builds')
    print('pending.draw AREA')
    print('running.label running builds')
    print('running.draw STACK')
    sys.exit(0)

gitlab = get_gitlab_instance()
db = gitlab.get_db_connection()
for state in ('pending', 'running'):
    cursor = db.cursor()
    cursor.execute("SELECT COUNT(*) FROM ci_builds WHERE status = '{state}'".format(state=state))
    print('{state}.value {value}'.format(state=state, value=cursor.fetchone()[0]))

