#!/usr/bin/env python
from lib import dirsize
from lib import get_gitlab_instance
import sys


gitlab = get_gitlab_instance()
registry_root = gitlab.get_registry_dir()

if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab docker registry disk usage')
    print('graph_vlabel docker registry disk usage')
    print('graph_args -l 0 --base 1024')
    print('graph_category gitlab')
    print('registry_size.label docker registry')
    print('registry_size.draw AREA')
    sys.exit(0)

registry_size = 0

try:
    registry_size = dirsize(registry_root)
except OSError as e:
    print(e)
    sys.exit(1)

print('registry_size.value ' + str(registry_size))
