#!/usr/bin/env python

from lib import get_gitlab_instance
import sys

labels = {
    'issue': 'Issue',
    'milestone': 'Milestone',
    'merge_request': 'MergeRequest',
    'note': 'Note',
    'project': 'Project',
    'snippet': 'Snippet',
    'user': 'User'
}

if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title GitLab open ToDo items')
    print('graph_vlabel ToDo items')
    print('graph_args -l 0')
    print('graph_category gitlab')
    print('issue.label Issues')
    print('issue.draw AREA')
    print('milestone.label Milestones')
    print('milestone.draw STACK')
    print('merge_request.label Merge Requests')
    print('merge_request.draw STACK')
    print('note.label Notes')
    print('note.draw STACK')
    print('project.label Projects')
    print('project.draw STACK')
    print('snippet.label Snippets')
    print('snippet.draw STACK')
    print('user.label Users')
    print('user.draw STACK')
    sys.exit(0)

gitlab = get_gitlab_instance()
db = gitlab.get_db_connection()

for label in labels:
    cursor = db.cursor()
    cursor.execute("SELECT COUNT(*) AS count FROM todos WHERE state = 'pending' AND target_type = %(target_type)s", {'target_type': labels[label]})
    print('{label}.value {value}'.format(label=label, value=cursor.fetchone()[0]))
    cursor.close()

db.close()

