#!/usr/bin/env python

# inspired by the redis munin plugin found at
# http://munin-monitoring.org/browser/munin-contrib/plugins/redis/redis_,
# written 2009 by Gleb Voronich <http://stanly.net.ua/>

from lib import get_gitlab_instance
import sys


if len(sys.argv) >= 2 and sys.argv[1] == 'config':
    print('graph_title Redis: Key Hit vs Miss Ratio')
    print('graph_vlabel per ${graph_period}')
    print('graph_category gitlab')
    print('graph_args -u 100 -l 0 -r --base 1000')
    print('hitratio.label hit ratio')
    print('hitratio.type GAUGE')
    print('hitratio.draw AREA')
    print('missratio.label miss ratio')
    print('missratio.type GAUGE')
    print('missratio.draw STACK')
    sys.exit(0)

gitlab = get_gitlab_instance()
redis_info = gitlab.get_redis_info()
keyspace_hits = int(redis_info['keyspace_hits'])
keyspace_misses = int(redis_info['keyspace_misses'])
total = keyspace_hits + keyspace_misses

if total > 0:
    hitratio = float(keyspace_hits) / float(total) * 100.0
    missratio = float(keyspace_misses) / float(total) * 100.0
    print('hitratio.value {:.2f}'.format(hitratio))
    print('missratio.value {:.2f}'.format(missratio))
else:
    print('hitratio.value {:.2f}'.format(50))
    print('missratio.value {:.2f}'.format(50))

